from wordcloud import WordCloud
import matplotlib.pyplot as plt
import numpy as np
import PIL.Image

text = open(file="FM-speech.txt", mode="r").read()

pythonMask = np.array(PIL.Image.open("./chidambaram.jpg"))

wc = WordCloud(
    stopwords=[
        "the",
        "and",
        "of",
        "to",
        "a",
        "in",
        "that",
        "we",
        "have",
        "I",
        "it",
        "for",
        "not",
        "on",
        "with",
        "he",
        "as",
        "you",
        "do",
        "at",
        "this",
        "but",
        "his",
        "by",
        "from",
        "they",
        "we",
        "say",
        "her",
        "she",
        "or",
        "an",
        "will",
        "my",
        "one",
        "all",
        "would",
        "there",
        "their",
        "what",
        "so",
        "up",
        "out",
        "if",
        "about",
        "who",
        "get",
        "which",
        "go",
        "me",
        "when",
        "make",
        "can",
        "like",
        "time",
        "no",
        "just",
        "him",
        "know",
        "take",
        "people",
        "into",
        "year",
        "your",
        "good",
        "some",
        "could",
        "them",
        "see",
        "other",
        "than",
        "then",
        "now",
        "look",
        "only",
        "come",
        "its",
        "over",
        "think",
        "also",
        "back",
        "after",
        "use",
        "two",
        "how",
        "our",
        "work",
        "first",
        "well",
        "way",
        "even",
        "new",
        "want",
        "because",
        "any",
        "these",
        "give",
        "day",
        "most",
        "us",
        "was",
        "be",
        "is",
        "are",
        "been",
        "crore",
        "has",
        "percent",
        "propose",
        "government",
        "had",
        "growth",
        "must",
        "scheme",
        "fund",
        
    ],
    mask=pythonMask,
    background_color="white",
    contour_color="black",
    max_words=100
).generate(text)




plt.imshow(wc)
plt.axis("off")
plt.show()
